### ISSUE TITLE
`AttributeError: 'tuple' object has no attribute 'get'` with magnet link

### ISSUE THREAD

**Issue by edgar-vincent** [hauxir/rapidbay#31]
Hi!

Thanks a lot for this project. 
rapidbay displays results, but I get the following error when I click on a torrent provided by a magnet link:

```
194.110.113.73 - - [23/Feb/2023:09:15:09 +0000] "GET /api/search/big%20buck%20bunny HTTP/1.0" 200 17464 "https://rapidbay.example.org/search/big%20buck%20bunny" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0"
[2023-02-23 09:15:22,589] ERROR in app: Exception on /api/torrent_url_to_magnet/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app.py", line 114, in decorated_function
    return f(*args, **kws)
  File "/app/app.py", line 185, in torrent_url_to_magnet
    magnet_link = torrent.make_magnet_from_torrent_file(filepath)
  File "/app/torrent.py", line 33, in make_magnet_from_torrent_file
    subj = metadata.get(b"info", {})
AttributeError: 'tuple' object has no attribute 'get'
194.110.113.73 - - [23/Feb/2023:09:15:22 +0000] "POST /api/torrent_url_to_magnet/ HTTP/1.0" 500 265 "https://rapidbay.example.org/torrent/https%3A%2F%2Fjackett.example.orgf%2Fdl%2Frutracker%2F%3Fjackett_apikey%3MYAPIKEY%26path%3DQ2ZESjhEZ09JNVo2TkxSSGxqaWxHR0lQaXJfUzhBNktjNEtLcVpFUGVKVzctZnlGdkRSQTFGZUU5SXU0LW9vR0ZIa2wxNWJXOWJwZDFaUVl2WTR5cEVieTlIeFlscTNwQm1jbzR4ckdJdE5ZRkkzdmdhRmJTU183dkJWM0dNVjRyNmtjTE9mWVpUT29ubFRzVlRQWUUxZzYyUjYxQTR4NEttNkZwU3NkN0RzOElJM0c%26file%3DBig%2BBuck%2BBunny%2B(Sacha%2BGoedegebure)%2B%255B2008%252C%2BBDRip%255D" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0"
```

Is it a problem with my setup?

Thanks a lot,
ev

**Comment by hauxir** [comment]
could you share a bit more info? Is your Jackett instance working correctly?

**Comment by edgar-vincent** [comment]
Sorry, I can't reproduce reliably. Sorry about the lack of info. I'll close this for now and reopen if I can provide steps to reproduce.
